# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  strickerapp-app:
    image: strickerapp
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://strickerapp-postgresql:5432/strickerapp
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://strickerapp-postgresql:5432/strickerapp
      - JHIPSTER_CACHE_REDIS_SERVER=redis://strickerapp-redis:6379
      - JHIPSTER_CACHE_REDIS_CLUSTER=false
      # - JHIPSTER_CACHE_REDIS_SERVER=redis://strickerapp-redis:6379
      # - JHIPSTER_CACHE_REDIS_CLUSTER=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:8080:8080
  strickerapp-postgresql:
    image: postgres:13.3
    # volumes:
    #   - ~/volumes/jhipster/strickerapp/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=strickerapp
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:5432:5432
  strickerapp-redis:
    image: redis:6.2.4
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:6379:6379
